// Predefined bot opponents for offline battles
export const BOTS = [
  {
    id: 'bot_1',
    name: 'Ignis',
    element: 'fire',
    level: 3,
    power: 22,
    evolution_stage: 1,
    difficulty: 'easy',
    difficultyLabel: 'Fácil',
    reward_xp: 25,
    reward_gold: 10,
  },
  {
    id: 'bot_2',
    name: 'Aquilla',
    element: 'water',
    level: 6,
    power: 40,
    evolution_stage: 2,
    difficulty: 'easy',
    difficultyLabel: 'Fácil',
    reward_xp: 35,
    reward_gold: 15,
  },
  {
    id: 'bot_3',
    name: 'Sylva',
    element: 'nature',
    level: 10,
    power: 65,
    evolution_stage: 2,
    difficulty: 'medium',
    difficultyLabel: 'Médio',
    reward_xp: 50,
    reward_gold: 25,
  },
  {
    id: 'bot_4',
    name: 'Voltex',
    element: 'electric',
    level: 14,
    power: 90,
    evolution_stage: 2,
    difficulty: 'medium',
    difficultyLabel: 'Médio',
    reward_xp: 70,
    reward_gold: 35,
  },
  {
    id: 'bot_5',
    name: 'Umbra',
    element: 'shadow',
    level: 18,
    power: 120,
    evolution_stage: 3,
    difficulty: 'hard',
    difficultyLabel: 'Difícil',
    reward_xp: 100,
    reward_gold: 50,
  },
  {
    id: 'bot_6',
    name: 'Pyraxis',
    element: 'fire',
    level: 25,
    power: 165,
    evolution_stage: 3,
    difficulty: 'hard',
    difficultyLabel: 'Difícil',
    reward_xp: 150,
    reward_gold: 75,
  },
  {
    id: 'bot_7',
    name: 'Leviathon',
    element: 'water',
    level: 35,
    power: 230,
    evolution_stage: 4,
    difficulty: 'expert',
    difficultyLabel: 'Extremo',
    reward_xp: 250,
    reward_gold: 120,
  },
];

export const DIFFICULTY_COLORS = {
  easy: { bg: 'bg-green-500/20', text: 'text-green-400', border: 'border-green-500/30' },
  medium: { bg: 'bg-yellow-500/20', text: 'text-yellow-400', border: 'border-yellow-500/30' },
  hard: { bg: 'bg-orange-500/20', text: 'text-orange-400', border: 'border-orange-500/30' },
  expert: { bg: 'bg-red-500/20', text: 'text-red-400', border: 'border-red-500/30' },
};